import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="bg-white absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 rounded-xl lg:w-[875px] lg:h-[600px]">
          <div className="absolute top-1/2 -translate-y-1/2 left-4">
            <img src="/images/bg-sidebar-desktop.svg" alt=""/>
            <div className="absolute top-[40px] left-[30px]">
              <div className="flex items-center">
                <div className="h-[36px] w-[36px] flex justify-center items-center border rounded-full text-white mr-4 ">1</div>
                <div className="text-white uppercase">
                  <p className="font-[300] text-gray-300 text-xs leading-none ">Step 1</p>
                  <p className=" text-sm font-bold">Your Info</p>
                </div>
              </div>
            </div>
          </div>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
